### ISSUE TITLE
how to hide clipboard toast message??

### ISSUE THREAD

**Issue by mchewry** [react-native-clipboard/clipboard#114]
i wanna show toast message when i succeed copy. 
but i think that failed showing toast message when i copied in android 11 device. 

how to hide clipboard toast message?
or how to show toast message in android 11 device?

**Comment by Naturalclar** [comment]
@mchewry 
for iOS, whenever clipboard copy happens, the OS shows a toast message for security purpose.
This cannot be removed from the clipboard package as it is a OS function

for android, you can implement your own toast using toast android
https://reactnative.dev/docs/toastandroid
