### ISSUE TITLE
Received warning asking to remove usages of `jcenter()` Maven repository from build scripts in RN 0.65.1

### ISSUE THREAD

**Issue by syuhadazulkifli** [react-native-clipboard/clipboard#119]
## Ask your Question

Hi. I just upgraded React Native version 0.65.1 and having trouble to run the emulator. 

This error appear, asking to remove jcenter() but this clipboard library still using jcenter(), right?

`WARNING:: Please remove usages of 'jcenter()' Maven repository from your build scripts and migrate your build to other Maven repositories.
This repository is deprecated and it will be shut down in the future.
See http://developer.android.com/r/tools/jcenter-end-of-service for more information.
Currently detected usages in: project ':react-native-clipboard_clipboard'`

Does anyone having the same issue?
Any suggestion to overcome this issue?

**Comment by matteodanelli** [comment]
Any plan on maven removal?

**Comment by Naturalclar** [comment]
@matteodanelli thanks for the PR! Should be closed with #127
