### ISSUE TITLE
Apple not approve application

### ISSUE THREAD

**Issue by erbilnas** [react-native-clipboard/clipboard#144]
## Environment
System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 37.11 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.0 => 0.66.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Platforms
iOS

## Description
Hi everyone! Recently, we tried to replace the old and deprecated RN Clipboard library with yours, but Apple rejected our applications. When we reverse just this change it's OK and approved, otherwise we can't use your library. Do you have any chance to check it? I'll share Apple's response with you; I hope it'll be helpful. Farewell!

> Dear Developer,
> 
> We identified one or more issues with a recent delivery for your app. Please correct the following issues, then upload again.
> 
> ITMS-90338: Non-public API usage - The app references non-public selectors in InstantPickerApp: estimatedProgress, initWithFrame:configuration:, isMainFrame, navigationType, newSocketQueueForConnectionFromAddress:onSocket:, onSuccess:, setNavigationDelegate:, setProcessPool:, socket:didAcceptNewSocket:, socket:didConnectToHost:port:, socket:didConnectToUrl:, socket:didReadData:withTag:, socket:didReadPartialDataOfLength:tag:, socket:didReceiveTrust:completionHandler:, socket:didWriteDataWithTag:, socket:didWritePartialDataOfLength:tag:, socket:shouldTimeoutReadWithTag:elapsed:bytesDone:, socket:shouldTimeoutWriteWithTag:elapsed:bytesDone:, socketDidCloseReadStream:, socketDidDisconnect:withError:, socketDidSecure:, targetFrame, userContentController, websiteDataStore. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at https://clicktime.symantec.com/3B5NFMBRDMdcEyHtR48XbX47GS?u=http%3A%2F%2Fdeveloper.apple.com%2Fsupport%2Ftechnical%2F

**Comment by luizmarques21** [comment]
I was facing the same problem on my app. So i ran `yarn install` on the root folder of my project, change to the ios folder, ran `pod install`, ran `npx pod-install` on the same ios folder and tried to re-archive. The Xcode uploaded my app successfully and Apple didn't reject this time.

Also, if you're using Codepush, try to run the codepush deploy command after update your app build on App Store
