### ISSUE TITLE
Build failed on android react native clipboard ^1.8.5 cannot find symbol  if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R)

### ISSUE THREAD

**Issue by banghia112** [react-native-clipboard/clipboard#151]
## Environment
System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 338.73 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - /opt/homebrew/bin/npm
    Watchman: HEAD-51a3b89 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/admin/.rvm/gems/ruby-2.7.4/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/javac
    Python: 3.8.6 - /Users/admin/.pyenv/shims/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
## Platforms
Android

## Versions

- Android: ^1.8.5
- iOS: ^1.8.5
- react-native-netinfo: ^5.9.6
- react-native: 0.63.2
- react: 16.13.1

## Description
Today i was building my debug app on android as usual but i got this: 
![image](https://user-images.githubusercontent.com/89189266/185871686-ae22740f-d995-43b7-b458-73ae5efb6a05.png)

i tried: running./gradlew clean and upgrading the library but didnt help
Any suggestions? 
Thanks

**Comment by Naturalclar** [comment]
@banghia112 
seems like the targetSDKVersion you're using doesn't include Build.VERSION_CODES.R , I'll make a fix for that

**Comment by Marcuspo** [comment]
+1

**Comment by arohablue** [comment]
+1

**Comment by Valentin-viseo** [comment]
+1

**Comment by Nziranziza** [comment]
+1

**Comment by Harsha171819** [comment]
+1

**Comment by sam9010** [comment]
Hi, my app have this error.
I use targetSdkVersion = 28 => if be 30, my project will not have error?
