### ISSUE TITLE
Task :react-native-community_clipboard:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by Anubhavjain786** [react-native-clipboard/clipboard#184]

**Comment by xaiamov** [comment]
Writing here to help somebody. I had the issue compiling my project for android.
```
> Task :app:mergeLibDexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeLibDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform classes.jar (project :react-native-community_clipboard) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, com.android.build.api.attributes.AgpVersionAttr=7.4.2, com.android.build.api.attributes.BuildTypeAttr=debug, com.android.build.gradle.internal.attributes.VariantAttr=debug, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: /Users/.../node_modules/@react-native-community/clipboard/android/build/intermediates/runtime_library_classes_jar/debug/classes.jar.
         > Unable to read jar file /Users/.../node_modules/@react-native-community/clipboard/android/build/intermediates/runtime_library_classes_jar/debug/classes.jar
```

The solution was to increase the `minSdkVersion` from 21 to 24 (for at least) in `android/build.gradle`.

**Comment by gtokman** [comment]
@xaiamov you're the goat! thank you 🙂

**Comment by manishprimathon** [comment]
@xaiamov  I have already minSdkVersion is 24, but I am getting below issue

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':react-native-community_clipboard:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

let me know, if any one can help me to solve this

**Comment by Jamal-ReachFirst** [comment]
> @xaiamov I have already minSdkVersion is 24, but I am getting below issue
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':react-native-community_clipboard:compileDebugJavaWithJavac'.
> 
> > Compilation failed; see the compiler error output for details.
> 
> let me know, if any one can help me to solve this

+1

**Comment by MuriloBarranco** [comment]
+1

**Comment by itsShivamBhalla** [comment]
same++

**Comment by Swapnil7387** [comment]
There is a patch for this bug and it is working fine:
Go to file: /@react-native-clipboard/clipboard/android/src/main/java/com/reactnativecommunity/clipboard/ClipboardModule.java
There search for the method: removeListeners(int count), it may be at line no: 240 
Replace the int parameter with double method with removeListeners(double count)
All credit goes to: https://github.com/react-native-clipboard/clipboard/issues/238#issuecomment-2083704956

**Comment by camboYY** [comment]
> Task :react-native-community_clipboard:compileDebugJavaWithJavac FAILED
/Users/yousyoeun/Documents/robotech-repo/cdrb-flow-app/node_modules/@react-native-community/clipboard/android/src/main/java/com/reactnativecommunity/clipboard/ClipboardModule.java:27: error: ReactApplicationContext is abstract; cannot be instantiated
    super(new ReactApplicationContext(context));
