### ISSUE TITLE
Monorepo REACT_NATIVE_NODE_MODULES_DIR error

### ISSUE THREAD

**Issue by mordonez-me** [react-native-clipboard/clipboard#215]
## Environment
System:
  OS: macOS 14.0
  CPU: (8) arm64 Apple M2
  Memory: 106.05 MB / 24.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.18.0
    path: ~/.local/share/nvm/v18.18.0/bin/node
  Yarn:
    version: 1.22.21
    path: ~/.local/share/nvm/v18.18.0/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.local/share/nvm/v18.18.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.11.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.1/15C65
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

info React Native v0.73.0 is now available (your project is running on v0.72.6).

## Platforms
Android

## Versions

- Android: 11
- iOS: NA
- react-native-netinfo: 
- react-native: 0.72.6
- react: 18.2.0

## Description
building with gradle does not find root node_modules, because this is run inside a folder and one level extra is needed. The current code is: 

![image](https://github.com/react-native-clipboard/clipboard/assets/2242042/7be5971c-1362-41ec-a4a3-0835988b7105)

Should be:

![image](https://github.com/react-native-clipboard/clipboard/assets/2242042/dad3fc99-f07c-4462-9d0b-2499b9c56a12)

**The extra ../ makes it work.**

## Reproducible Demo
You need to set up a monorepo with pnpm and hoisted.

**Comment by JClackett** [comment]
Yep, have the exact same thing since version 1.13.0/1.13.1

**Comment by Titozzz** [comment]
Created a PR :) with a comment showing where the issue came from 🥲
