### ISSUE TITLE
How to remove the default toast msg 'copied'

### ISSUE THREAD

**Issue by nawazokz** [react-native-clipboard/clipboard#245]
hello everyone, When I copy string using Clipboard.setString(str); it show the default toast msg 'copied' which i want to hide or remove and instead use custom toast msg.
How can be I achieve this

**Comment by ishant-1428** [comment]
Hiding the default toast is impossible from Android 13. Since the toast is shown by Android when setting Clipboard data.
You can refer to this for more information :
https://developer.android.com/develop/ui/views/touch-and-input/copy-paste#Feedback

**Comment by Naturalclar** [comment]
closing as it's specification on android side
