### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by necolas** [react-native-clipboard/clipboard#5]
## Describe the Feature

Clipboard API should support web environments

## Possible Implementations

https://github.com/necolas/react-native-web/blob/0.11.2/packages/react-native-web/src/exports/Clipboard/index.js

**Comment by Taym95** [comment]
Hey @necolas, I just was wondering why we don't use the [Clipboard_API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API)?

**Comment by emac3** [comment]
what about using the new Clipboard Web API and falling back to copying react-native-web implementation where not supported?
