### ISSUE TITLE
not able to install clipboard with react 7.14

### ISSUE THREAD

**Issue by mbishtnew** [react-native-clipboard/clipboard#82]
## Ask your Question

/node_modules/@react-native-community/clipboard/dist/NativeClipboard.js
Module not found: Can't resolve 'react-native' in 'C:\Workspace\sample\my-app\node_modules\@react-native-community\clipboard\dist'

package.json

 "dependencies": {
    "@fluentui/react": "^7.149.2",
    "@juggle/resize-observer": "^3.2.0",
    "@react-native-community/clipboard": "1.5.0",
    "axios": "^0.21.0",
    "constate": "^3.1.0",
    "core-js": "^3.6.5",
    "es6-promise": "^4.2.8",
    "oidc-client": "^1.10.1",
    "react": "^16.14.0",
    "react-dom": "^16.14.0",
    "react-query": "^2.25.2",
    "react-query-devtools": "^2.6.1",
    "react-router-dom": "^5.2.0",
    "react-sortable-tree": "^2.2.0",
    "react-sortable-tree-theme-file-explorer": "^2.0.0",
    "react-use-measure": "^2.0.3",
    "store": "^2.0.12"
  },

"devDependencies": {
    "@babel/core": "^7.12.3",
    "@babel/polyfill": "^7.12.1",
    "@babel/preset-env": "^7.12.1",
    "@hot-loader/react-dom": "^17.0.0",
    "@types/find-process": "1.2.0",
    "@types/office-js": "^1.0.146",
    "@types/office-runtime": "^1.0.17",
    "@types/react": "^16.9.55",
    "@types/react-dom": "^16.9.9",
    "@types/react-hot-loader": "^4.1.1",
    "@types/react-router-dom": "^5.1.6",
    "@types/store": "^2.0.2",
    "@types/webpack": "^4.41.24",
    "@types/webpack-dev-server": "^3.11.1",
    "babel-loader": "^8.1.0",
    "clean-webpack-plugin": "^3.0.0",
    "copy-webpack-plugin": "^6.2.1",
    "css-loader": "^5.0.0",
    "eslint-config-office-addins": "^1.0.19",
    "eslint-plugin-office-addins": "^0.1.7",
    "eslint-plugin-react": "^7.21.5",
    "file-loader": "^6.2.0",
    "find-process": "^1.4.4",
    "html-webpack-plugin": "^4.5.0",
    "husky": "^4.3.0",
    "mini-css-extract-plugin": "^1.2.1",
    "office-addin-cli": "^1.0.13",
    "office-addin-debugging": "^3.0.37",
    "office-addin-dev-certs": "^1.5.7",
    "office-addin-lint": "^1.0.27",
    "office-addin-manifest": "1.5.9",
    "pretty-quick": "^3.1.0",
    "react-hot-loader": "^4.13.0",
    "style-loader": "^2.0.0",
    "ts-loader": "^8.0.7",
    "tsconfig-paths-webpack-plugin": "^3.3.0",
    "typescript": "^4.0.5",
    "webpack": "^4.44.2",
    "webpack-cli": "^3.3.12",
    "webpack-dev-server": "^3.11.0",
    "@types/react-sortable-tree": "^0.3.12"
  }

**Comment by lukw34** [comment]
I have the same issue, can someone look at this?

**Comment by Naturalclar** [comment]
This module needs to be used with react-native.
It seems like your project is working with react for web. You will need to integrate react-native-web in order to use this package.
